from enum import Enum


class StatusEnum(Enum):
    SHIPMENT_DELAYED = "SHIPMENT_DELAYED"
    NOT_SERVICEABLE = "NOT_SERVICEABLE"
    PLACED = "PLACED"
    DELIVERY_FAILED = "DELIVERY_FAILED"
    PICKUP_FAILED = "PICKUP_FAILED"
    OUT_FOR_PICKUP = "OUT_FOR_PICKUP"
    ORIGIN_CITY_OUT = "ORIGIN_CITY_OUT"
    IN_TRANSIT = "IN_TRANSIT"
    ORIGIN_CITY_IN = "ORIGIN_CITY_IN"
    RTO_INITIATED = "RTO_INITIATED"
    OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY"
    SHIPMENT_HELD = "SHIPMENT_HELD"
    CANCELLED = "CANCELLED"
    CONTACT_CUSTOMER_CARE = "CONTACT_CUSTOMER_CARE"
    RTO_DELIVERED = "RTO_DELIVERED"
    PICKED = "PICKED"
    DESTINATION_HUB_IN = "DESTINATION_HUB_IN"
    DELIVERED = "DELIVERED"
